/** Ürün vitrini. Yeni kategori satmak için bu listeyi değiştirmek yeterli. */
const SHOP = {
  name: "Rota",
  line: "Araç aksesuarı",
};

const CATEGORIES = [
  { id: "ic", name: "İç mekan" },
  { id: "elektronik", name: "Elektronik" },
  { id: "duzen", name: "Düzen" },
  { id: "bakim", name: "Bakım" },
  { id: "guvenlik", name: "Güvenlik" },
];

const PRODUCTS = [
  {
    id: "telefon-tutucu",
    name: "Manyetik telefon tutucu",
    category: "elektronik",
    price: 449,
    compare: 590,
    tone: "#1e2430",
    mark: "M",
    blurb: "Havalandırmaya takılan, tek elle çıkan tutucu.",
    details: ["Çoğu havalandırma ızgarasına uyar", "Manyetik plaka dahil", "Sürüş sırasında görüşü kapatmaz"],
  },
  {
    id: "bagaj-duzenleyici",
    name: "Katlanır bagaj düzenleyici",
    category: "duzen",
    price: 890,
    compare: 0,
    tone: "#3a332c",
    mark: "B",
    blurb: "Market filesi ve şarj kablosu aynı gözde karışmasın.",
    details: ["Katlanınca düzleşir", "Çıkarılabilir bölmeler", "Bagaj paspasının üstüne oturur"],
  },
  {
    id: "direksiyon-kilifi",
    name: "Dikişli direksiyon kılıfı",
    category: "ic",
    price: 690,
    compare: 840,
    tone: "#2a2420",
    mark: "D",
    blurb: "İnce dikiş, kaymayan iç yüzey.",
    details: ["Standart çap direksiyonlar", "İğne ve ip seti kutuda", "Yazın ele yapışmaz kumaş"],
  },
  {
    id: "ambiyans",
    name: "İç ambiyans ışık kiti",
    category: "elektronik",
    price: 1290,
    compare: 0,
    tone: "#172028",
    mark: "A",
    blurb: "Ayak boşluğu ve konsol için kısılabilir şerit.",
    details: ["USB besleme", "Üç renk", "Kablo klipsleri dahil"],
  },
  {
    id: "kamera",
    name: "Ön cam kamera",
    category: "guvenlik",
    price: 2490,
    compare: 2890,
    tone: "#14181c",
    mark: "K",
    blurb: "Döngülü kayıt, park halinde darbe algılama.",
    details: ["Full HD", "32 GB kart önerilir, kutuda yok", "Emniyet camına yapışkan ayak"],
  },
  {
    id: "paspas",
    name: "Havuzlu paspas seti",
    category: "ic",
    price: 1590,
    compare: 0,
    tone: "#243028",
    mark: "P",
    blurb: "Ön iki parça. Çamur kenarda kalır.",
    details: ["Kesilebilir kenar", "Altı kaymaz", "Hortumla yıkanır"],
  },
  {
    id: "koltuk-arki",
    name: "Koltuk arkası düzenleyici",
    category: "duzen",
    price: 540,
    compare: 690,
    tone: "#3d342c",
    mark: "S",
    blurb: "Tablet, şişe ve ıslak mendil cebi.",
    details: ["Başlığa asılır", "Çocuk koltuğu ile birlikte denenmeli", "Çıkarılabilir alt tepsi"],
  },
  {
    id: "sarj",
    name: "Çift giriş araç şarjı",
    category: "elektronik",
    price: 320,
    compare: 0,
    tone: "#22262c",
    mark: "Ç",
    blurb: "USB-C ve USB-A. Kısa yolculukta telefon bitmesin.",
    details: ["12V çakmaklık girişi", "Aşırı akım koruması", "Kablo dahil değil"],
  },
  {
    id: "guneslik",
    name: "Katlanır ön cam güneşlik",
    category: "ic",
    price: 280,
    compare: 360,
    tone: "#3a3428",
    mark: "G",
    blurb: "Öğlen parkta direksiyonun yanmaması için.",
    details: ["Akordiyon katlama", "Çoğu binek cama uyar", "Ayna askısı cebi"],
  },
  {
    id: "basinc",
    name: "Dijital lastik basınç ölçer",
    category: "bakim",
    price: 410,
    compare: 0,
    tone: "#1c2830",
    mark: "L",
    blurb: "Benzinlikte tahmin etmeden bak.",
    details: ["Bar ve PSI", "Arka ışık", "Pil dahil"],
  },
  {
    id: "file",
    name: "Bagaj filesi",
    category: "duzen",
    price: 260,
    compare: 0,
    tone: "#2c2824",
    mark: "F",
    blurb: "Şişe ve çanta frenlemede kaymasın.",
    details: ["Dört kanca", "Esnek ağ", "Boşken katlanır"],
  },
  {
    id: "kokpit",
    name: "Kokpit temizlik seti",
    category: "bakim",
    price: 350,
    compare: 420,
    tone: "#26241f",
    mark: "T",
    blurb: "Toz bezi, fırça ve mat yüzey sıvısı.",
    details: ["Üç parça", "Göstergeye film bırakmayan bez", "Ev kullanımı için değil, araç yüzeyi"],
  },
];
